/**
 * ÖZGÜN editoryal rehber yazıları — insan kalitesinde, uzun ve gerçek değer veren içerik.
 * Şablon (blogSeo.ts) DEĞİL; AdSense "değerli içerik" ölçütü + kullanıcı güveni için elle yazıldı.
 */
import type { Post } from "./blog";

export const ORIGINAL_POSTS: Post[] = [
  {
    slug: "tarayici-oyunlari-nedir-nasil-calisir",
    title: "Tarayıcı Oyunları Nedir ve Nasıl Çalışır? HTML5 ve WebGL Rehberi",
    date: "2026-07-04",
    excerpt:
      "İndirmeden, kurulum yapmadan oynanan tarayıcı oyunlarının arkasındaki teknolojiyi, avantajlarını ve sınırlarını sade bir dille anlattık.",
    body: [
      "Bir bağlantıya tıklıyorsun ve birkaç saniye içinde oyun açılıyor; ne mağazadan indirme, ne kurulum, ne de büyük bir dosya bekleme. Tarayıcı oyunlarının cazibesi tam olarak bu sadelikte. Peki bu oyunlar telefonuna veya bilgisayarına hiçbir şey yüklemeden nasıl çalışıyor? Bu yazıda perde arkasındaki teknolojiyi, neden bu kadar yaygınlaştığını ve nelerin mümkün olup olmadığını anlaşılır bir dille açıklıyoruz.",
      "## Tarayıcı oyunu tam olarak nedir?",
      "Tarayıcı oyunu, ayrı bir uygulama gerektirmeden doğrudan web tarayıcının (Chrome, Safari, Firefox, Edge) içinde çalışan oyundur. Oyunun tüm kodu ve görselleri, tıpkı bir web sitesini açar gibi, o an internetten yüklenir ve tarayıcı bunları ekranında çalıştırır. Yani oyun aslında ziyaret ettiğin bir web sayfasının içinde yaşar.",
      "Bu yaklaşımın en büyük farkı, oyunun cihazından bağımsız olmasıdır. Aynı oyun; Windows bilgisayarda, Android telefonda ve iPhone'da, ekstra bir sürüm gerekmeden çalışabilir. Çünkü hepsinin ortak noktası bir web tarayıcısına sahip olmalarıdır.",
      "## Perde arkasındaki teknoloji: HTML5, JavaScript ve WebGL",
      "Eskiden tarayıcı oyunları çoğunlukla Flash adlı bir eklentiyle çalışırdı. Flash artık tamamen kullanımdan kalktı ve yerini modern, açık web standartları aldı. Bugün tarayıcı oyunlarını ayakta tutan üç temel teknoloji var:",
      "- **HTML5 Canvas:** Tarayıcıya çizim yapma yeteneği kazandıran bir 'tuval'. 2D oyunların büyük kısmı karakterleri, arka planları ve efektleri bu tuval üzerine çizer.",
      "- **JavaScript:** Oyunun beynidir. Karakterin hareketini, çarpışmaları, skoru, yapay zekâyı ve oyun kurallarını yöneten kod bu dilde yazılır.",
      "- **WebGL:** Tarayıcının bilgisayarındaki grafik kartını (GPU) kullanmasını sağlayan teknoloji. Yüksek grafikli 3D oyunların akıcı çalışmasını mümkün kılan şey budur; adeta bir konsol deneyimini tarayıcıya taşır.",
      "Bu üçlü sayesinde bugün tarayıcıda basit bir yılan oyunundan, gerçek zamanlı çok oyunculu bir nişancı oyununa kadar geniş bir yelpaze çalışabiliyor. [3D oyunlar bölümü](/kategori/3d) WebGL'in gücünü en iyi gösteren yerdir.",
      "## Neden bu kadar popüler?",
      "Tarayıcı oyunlarının hızla yayılmasının birkaç somut nedeni var:",
      "- **Anında erişim:** İndirme ve kurulum beklemek yok. Tıkla, oyna. Kısa bir molada hızlı eğlence için ideal.",
      "- **Yer kaplamaz:** Telefonunun hafızasını doldurmaz. Onlarca oyunu tek tek indirmek yerine hepsine tek siteden ulaşırsın.",
      "- **Platform bağımsızdır:** İş yerindeki bilgisayardan başladığın bir oyuna, evde telefondan devam edebilirsin.",
      "- **Güvenlidir:** Tarayıcı oyunları 'sandbox' denen korumalı bir alanda çalışır; cihazının dosyalarına doğrudan erişemezler.",
      "## Sınırları neler?",
      "Her teknolojinin olduğu gibi tarayıcı oyunlarının da sınırları var. Devasa dosya boyutuna sahip AAA konsol oyunları (ki bunlar onlarca gigabayt olabilir) tarayıcıda çalışmaz; çünkü her şeyin makul sürede yüklenmesi gerekir. Ayrıca performans, cihazının gücüne ve internet hızına bağlıdır. Yine de HTML5 ve WebGL her yıl güçleniyor ve tarayıcıda mümkün olanın sınırı sürekli genişliyor.",
      "## Özetle",
      "Tarayıcı oyunları, modern web standartları (HTML5, JavaScript, WebGL) sayesinde hiçbir şey indirmeden, her cihazda, güvenli biçimde oynanan oyunlardır. Sadelik, hız ve erişilebilirlik onları milyonlarca oyuncu için ilk tercih hâline getiriyor. Merak ettiğin her türden binlerce örneği [tüm oyunlar sayfasında](/oyunlar) ücretsiz deneyebilirsin.",
    ],
  },
  {
    slug: "cocuklar-icin-guvenli-oyun-secme-rehberi",
    title: "Ebeveynler İçin Güvenli Oyun Rehberi: Çocuğunuz İçin Doğru Oyunu Seçmenin 8 Yolu",
    date: "2026-07-04",
    excerpt:
      "Çocuğunuzun yaşına uygun, güvenli ve eğitici oyunları seçerken dikkat etmeniz gereken 8 pratik başlık; ekran süresi ve sağlıklı alışkanlıklar dahil.",
    body: [
      "Dijital oyunlar, doğru seçildiğinde çocukların el-göz koordinasyonundan problem çözmeye kadar birçok beceriyi geliştirebilir. Ancak her oyun her yaşa uygun değildir ve internet, ebeveynler için bazen kafa karıştırıcı bir yer olabilir. Bu rehberde, çocuğunuz için güvenli ve faydalı oyunlar seçerken işinize yarayacak sekiz pratik başlığı bir araya getirdik.",
      "## 1. Yaş uygunluğunu kontrol edin",
      "Bir oyunun görselleri renkli ve sevimli diye içeriğinin yaşa uygun olduğunu varsaymayın. Oyunun temasına, zorluk seviyesine ve varsa şiddet öğelerine bakın. Küçük yaş grupları için renk, şekil ve eşleştirme gibi sade mekanikler; biraz daha büyük çocuklar için hafif strateji ve bulmaca oyunları idealdir.",
      "## 2. Şiddet ve korku öğelerinden kaçının",
      "Küçük çocuklar için gerçekçi şiddet, silah veya korku temalı oyunlardan uzak durmak en sağlıklısıdır. Bunun yerine yapıcı temalı oyunları tercih edin: inşa etme, boyama, hayvan bakımı, yemek yapma gibi. [Çocuk kategorisi](/kategori/cocuk) ve [boyama oyunları](/boyama-oyunlari) bu açıdan güvenli başlangıç noktalarıdır.",
      "## 3. Eğitici değeri olan oyunları önceliklendirin",
      "Oyun yalnızca eğlence değil, öğrenme fırsatı da olabilir. Sayı ve harf tanıma, hafıza, mantık ve yaratıcılık geliştiren oyunlar, ekran süresini daha anlamlı hâle getirir. [Bulmaca](/kategori/bulmaca) ve [zekâ oyunları](/kategori/zeka) çocuğun düşünme becerisini eğlenceli biçimde çalıştırır.",
      "## 4. Reklamlara ve satın almalara dikkat edin",
      "Bazı oyunlar agresif reklamlar veya uygulama içi satın almalar içerebilir. Çocuğunuzun yanlışlıkla bir şey satın almasını önlemek için cihazınızda satın alma onayı/şifre ayarlayın. Tarayıcı oyunlarının avantajı, çoğunun indirme veya hesap gerektirmeden, tamamen ücretsiz oynanmasıdır.",
      "## 5. Ekran süresini birlikte belirleyin",
      "Uzmanlar, çocuklar için makul ve tutarlı ekran süresi sınırları önerir. Süreyi bir 'ceza' gibi değil, birlikte kararlaştırılan bir plan gibi sunmak daha etkilidir. Oyun molalarında gözlerin dinlenmesi için kısa aralar vermek de önemlidir.",
      "## 6. Oyunu önce siz deneyin",
      "Bir oyunu çocuğunuza açmadan önce birkaç dakika kendiniz oynayın. Kontrollerin çocuğunuza uygun olup olmadığını, içeriğin beklentinizi karşılayıp karşılamadığını böyle en iyi anlarsınız. Bu küçük adım, sonradan yaşanacak sürprizleri büyük ölçüde önler.",
      "## 7. Birlikte oynayın",
      "Mümkün olduğunda çocuğunuzla birlikte oynayın. [2 kişilik oyunlar](/2-kisilik-oyunlar) hem eğlenceli bir aile aktivitesi sunar hem de çocuğunuzun neyle ilgilendiğini yakından görmenizi sağlar. Birlikte geçirilen bu zaman, ekran başındaki deneyimi paylaşılan bir keyfe dönüştürür.",
      "## 8. Sağlıklı alışkanlıkları teşvik edin",
      "Oyunun; ödev, uyku, fiziksel aktivite ve arkadaşlarla vakit gibi diğer önemli şeylerin yerini almadığından emin olun. Denge kurulduğunda dijital oyunlar, çocuğun gününün keyifli ve zararsız bir parçası olabilir.",
      "## Sonuç",
      "Güvenli oyun seçimi, birkaç basit alışkanlıkla kolayca yönetilebilir: yaşa uygunluk, yapıcı içerik, makul süre ve ebeveyn ilgisi. Bu sekiz başlığı bir kontrol listesi gibi kullanarak çocuğunuz için hem eğlenceli hem güvenli bir oyun ortamı oluşturabilirsiniz. Ailelere uygun seçenekler için [çocuklar için oyunlar koleksiyonuna](/cocuklar-icin-oyunlar) göz atabilirsiniz.",
    ],
  },
  {
    slug: "ucretsiz-oyunlar-nasil-ucretsiz-gelir-modeli",
    title: "Ücretsiz Oyunlar Nasıl Ücretsiz Olabiliyor? Oyun Portallarının Gelir Modeli",
    date: "2026-07-03",
    excerpt:
      "Binlerce oyun neden ve nasıl ücretsiz? Oyun portalları parayı nereden kazanır, oyun geliştiriciler bundan nasıl pay alır — şeffaf bir açıklama.",
    body: [
      "Binlerce oyunu ücretsiz ve indirmeden oynayabildiğin bir siteye ilk kez girdiğinde akla mantıklı bir soru geliyor: madem her şey bedava, bu işin parası nereden geliyor? Bu yazıda oyun portallarının gelir modelini, oyun geliştiricilerin bundan nasıl pay aldığını ve neden bu sistemin herkes için sürdürülebilir olduğunu şeffaf biçimde açıklıyoruz.",
      "## Kısa cevap: reklam gelir paylaşımı",
      "Ücretsiz oyun portallarının büyük kısmı, oyunlar içinde veya çevresinde gösterilen reklamlardan gelir elde eder. Sen bir oyunu oynarken bölüm aralarında kısa bir reklam görürsün; işte o reklam, hem oyunu yapan geliştiriciye hem de oyunu yayınlayan siteye küçük bir gelir sağlar. Kimseden para alınmaz; sistem tamamen reklamla döner.",
      "## Oyun geliştiriciler bu işin neresinde?",
      "Tarayıcı oyunlarının çoğu, bağımsız stüdyolar veya geliştiriciler tarafından yapılır. Bu geliştiriciler oyunlarını, GameMonetize, GameDistribution ve GamePix gibi 'oyun dağıtım ağları' üzerinden yayınlar. Bu ağlar, oyunu binlerce siteye ulaştırır ve oluşan reklam gelirini geliştiriciyle paylaşır. Yani bir oyun ne kadar çok oynanırsa, onu yapan kişi de o kadar kazanır. Bu, geliştiricileri yeni ve daha iyi oyunlar yapmaya teşvik eden sağlıklı bir döngüdür.",
      "## Portal (site) ne yapar, neden gerekir?",
      "Oyun portalları bu ekosistemde önemli bir rol oynar: dağınık hâldeki binlerce oyunu tek bir yerde toplar, düzenler, kategorilere ayırır ve keşfedilmesini kolaylaştırır. İyi bir portal; hızlı yüklenen, reklamı ölçülü, mobil uyumlu ve kolay gezilen bir deneyim sunar. Bunun karşılığında, oyunlardan gelen reklam gelirinin bir kısmını alır. Kısacası portal, oyuncu ile binlerce oyun arasında düzenli bir vitrin görevi görür.",
      "## Peki oyuncu ne kaybeder?",
      "Doğrudan bir para kaybı yok. Karşılığında yalnızca ara sıra kısa reklamlar izlersin ve bazı siteler kişiselleştirilmiş reklam için çerez kullanır (bunu gizlilik ayarlarından yönetebilirsin). Bu model sayesinde:",
      "- Oyunlar tamamen ücretsiz kalır.",
      "- Üyelik veya kredi kartı zorunluluğu olmaz.",
      "- Geliştiriciler emeğinin karşılığını alır ve üretmeye devam eder.",
      "## Şeffaflık neden önemli?",
      "Bir sitenin gelirini nasıl elde ettiğini açıkça söylemesi, güvenin temelidir. 'Ücretsiz' kelimesinin arkasında gizli bir tuzak olup olmadığını merak etmek doğaldır; iyi bir portalda böyle bir tuzak yoktur. Reklam gösterimi ve çerez kullanımı, gizlilik politikasında açıkça belirtilir ve kullanıcıya seçim hakkı sunulur.",
      "## Sonuç",
      "Ücretsiz oyunlar, reklam gelir paylaşımına dayanan sağlıklı bir ekosistem sayesinde gerçekten ücretsizdir. Oyuncu bedava eğlenir, geliştirici emeğinin karşılığını alır, portal ise bu ikisini bir araya getirir. Sen sadece oyununu seç ve oyna — gerisi perde arkasında, kimseden ücret alınmadan halloluyor. Dilersen [en çok oynanan oyunlardan](/en-cok-oynanan-oyunlar) başlayabilirsin.",
    ],
  },
  {
    slug: "tarayici-oyunlari-neden-takilir-performans-rehberi",
    title: "Tarayıcı Oyunları Neden Takılır? Performans Sorunlarını Çözme Rehberi",
    date: "2026-07-03",
    excerpt:
      "Oyun donuyor, geç açılıyor veya kasıyorsa bunun birkaç bilinen nedeni var. Tarayıcıda daha akıcı oyun deneyimi için pratik çözümler.",
    body: [
      "Bir oyunu açtın ama geç yükleniyor, ortasında donuyor veya kontroller geç tepki veriyor. Bu sinir bozucu ama çoğu zaman kolayca çözülebilen bir durum. Tarayıcı oyunlarının performansı; cihazının gücü, internet hızı ve tarayıcı ayarları gibi birkaç faktöre bağlıdır. Bu rehberde takılmaların nedenlerini ve daha akıcı bir deneyim için atabileceğin somut adımları sıraladık.",
      "## 1. Çok fazla açık sekme",
      "Tarayıcıda aynı anda onlarca sekme açıksa, bunların her biri cihazının belleğinden pay alır ve oyuna daha az kaynak kalır. En hızlı çözüm: oyunu oynamadan önce ihtiyacın olmayan sekmeleri kapatmak. Özellikle video veya müzik çalan sekmeler performansı belirgin düşürür.",
      "## 2. Donanım hızlandırması kapalı",
      "Tarayıcıların 'donanım hızlandırma' adında bir ayarı vardır. Bu ayar, grafik işlerini bilgisayarın grafik kartına (GPU) devrederek özellikle 3D ve WebGL oyunlarını çok daha akıcı hâle getirir. Genelde varsayılan olarak açıktır; kapalıysa tarayıcının ayarlarından açman akıcılığı ciddi biçimde artırabilir.",
      "## 3. Yavaş veya kararsız internet",
      "Oyunun ilk yüklenmesi internet hızına bağlıdır; özellikle [online ve çok oyunculu oyunlar](/online) sürekli bağlantı gerektirdiği için kararsız internette takılır. Mümkünse Wi-Fi'ye yakın ol veya kablolu bağlantı kullan. Online oyunlarda 'ping' (gecikme) yüksekse, oyunun sende değil bağlantında sorun olabilir.",
      "## 4. Eski tarayıcı sürümü",
      "Tarayıcın güncel değilse, modern oyunların kullandığı yeni web teknolojilerini tam desteklemeyebilir. Tarayıcını (Chrome, Firefox, Edge, Safari) en son sürüme güncellemek hem performansı hem güvenliği artırır.",
      "## 5. Arka planda çalışan programlar",
      "Bilgisayarında arka planda çalışan ağır programlar (büyük indirmeler, güncellemeler, başka oyunlar) belleği ve işlemciyi meşgul eder. Oyun oynarken bunları geçici olarak kapatmak fark yaratır. Telefonlarda ise pil tasarrufu modu performansı bilinçli olarak düşürebilir; akıcılık istiyorsan bu modu kapatmayı dene.",
      "## 6. Önbellek birikmesi",
      "Zamanla tarayıcının önbelleği dolar ve bu bazen sayfaların ve oyunların yavaş açılmasına yol açabilir. Tarayıcı ayarlarından önbelleği temizlemek, takılan bir oyunu çoğu zaman canlandırır.",
      "## Mobilde ek ipuçları",
      "- Uygulama gibi kullanmak için siteyi 'ana ekrana ekle' ile kaydet; tam ekran ve daha stabil çalışır.",
      "- Çok fazla uygulama açıksa telefonu bir kez yeniden başlatmak belleği tazeler.",
      "- Düşük depolama alanı da performansı etkiler; gereksiz dosyaları temizle.",
      "## Sonuç",
      "Tarayıcı oyunlarındaki takılmaların çoğu; açık sekmeler, kapalı donanım hızlandırma, yavaş internet veya güncel olmayan tarayıcıdan kaynaklanır. Bu basit adımları uyguladığında oyunların büyük kısmı akıcı çalışır. Sorun tek bir oyunda değil hepsindeyse muhtemelen cihaz/bağlantı kaynaklıdır; tek bir oyundaysa o oyunu yeniden yüklemek çoğu zaman yeterli olur.",
    ],
  },
  {
    slug: "io-oyunlari-nedir-nasil-ortaya-cikti",
    title: ".io Oyunları Nedir ve Nasıl Ortaya Çıktı? Çok Oyunculu Arenaların Yükselişi",
    date: "2026-07-02",
    excerpt:
      "Basit kurallar, anında başlayan çok oyunculu maçlar: .io türünün nasıl doğduğunu, neden bu kadar sevildiğini ve nasıl oynandığını anlattık.",
    body: [
      "Son yılların en dikkat çekici oyun türlerinden biri hiç şüphesiz '.io' oyunları oldu. Basit görselleri, anında başlayan çok oyunculu maçları ve 'öğrenmesi kolay, ustalaşması zor' yapısıyla milyonlarca oyuncuyu kendine bağladılar. Peki bu tür tam olarak nedir, adı nereden geliyor ve neden bu kadar popüler oldu?",
      "## '.io' adı nereden geliyor?",
      "İsim aslında teknik bir tesadüf. Türün ilk büyük örnekleri, adresinin sonu '.io' ile biten alan adlarında yayınlandı. Bu oyunlar viral biçimde yayılınca, '.io' ifadesi zamanla belirli bir oyun tarzının ismi hâline geldi: tarayıcıda oynanan, anında başlayan, çok oyunculu, basit görselli hayatta kalma ve büyüme oyunları.",
      "## Türün temel mantığı",
      "Çoğu .io oyununun ortak bir DNA'sı vardır: küçük başlarsın, bir şeyler toplayarak büyürsün ve daha büyük olan seni yerken, sen de daha küçük olanları yutmaya çalışırsın. Amaç genellikle hayatta kalarak arenanın en büyüğü olmaktır. Kurallar birkaç saniyede öğrenilir ama gerçek ustalık; ne zaman risk alacağını, ne zaman kaçacağını bilmekte gizlidir.",
      "## Neden bu kadar sevildi?",
      "- **Anında oyun:** Uzun menüler, seviye atlama veya kurulum yok. Tıkla, saniyeler içinde çok oyunculu bir maçın içindesin.",
      "- **Adil rekabet:** Herkes küçük başlar; para veya seviye değil, beceri ve strateji kazandırır.",
      "- **Kısa seanslar:** Bir maç birkaç dakika sürer, mola için idealdir; ama 'bir tur daha' hissi bağımlılık yapar.",
      "- **Çok oyunculu heyecan:** Ekrandaki diğer karakterler gerçek insanlardır; bu, her maçı öngörülemez ve canlı kılar.",
      "## Nasıl daha iyi oynanır?",
      "Yeni başlayanların en sık hatası, erken oyunda aşırı agresif olmaktır. Çoğu .io oyununda güvenli büyümek, kör bir saldırıdan daha kazançlıdır. Haritanın kenarlarını kullanarak köşeye sıkışmaktan kaçın, kendinden büyüklerden uzak dur ve fırsatını beklemeyi öğren. Sabır, bu türde en değerli beceridir.",
      "## Bugün .io oyunları",
      "Tür başlangıçtaki basit büyüme oyunlarından çok daha ileri gitti. Bugün nişancı, yarış, hayatta kalma ve strateji temalı yüzlerce .io oyunu var; hepsi aynı çekirdek fikri paylaşıyor: anında başlayan gerçek zamanlı çok oyunculu rekabet. Türün en iyi örneklerini [.io oyunları kategorisinde](/kategori/io) ve daha geniş bir seçki için [ücretsiz online oyunlar koleksiyonunda](/ucretsiz-online-oyunlar) bulabilirsin.",
      "## Sonuç",
      "'.io' oyunları, sadelik ile derinliği ustaca birleştiren bir türdür: birkaç saniyede öğrenilir, ama ustalaşması saatler alır. Anında başlayan çok oyunculu yapısı, onları kısa molaların ve uzun keyifli seansların favorisi yaptı. Rekabeti ve hızlı aksiyonu seviyorsan, bu tür tam sana göre.",
    ],
  },
  {
    slug: "oynava-originals-golgediyari-blokkraft-hikayesi",
    title: "Oynava Originals: GölgeDiyarı ve BlokKraft Nasıl Geliştirildi?",
    date: "2026-07-09",
    excerpt:
      "Oynava'nın kendi stüdyosunda sıfırdan geliştirdiği iki özgün oyun: izometrik aksiyon-RPG GölgeDiyarı ve sandbox inşa oyunu BlokKraft'ın hikâyesi.",
    body: [
      "OYNAVA'daki oyunların büyük kısmı bağımsız stüdyolardan derlenip yayınlanır; ama Oynava Originals bunun dışında bir bölümdür. Bu koleksiyondaki oyunlar, kod satırından son piksele kadar kendi ekibimiz tarafından sıfırdan yazılır. Bu yazıda, koleksiyonun ilk iki üyesi olan GölgeDiyarı ve BlokKraft'ın nasıl şekillendiğini anlatıyoruz.",
      "## GölgeDiyarı: izometrik bir aksiyon-RPG",
      "[GölgeDiyarı](/oyun/ov-golgediyari/golgediyari), klasik izometrik aksiyon-RPG türüne (Diablo tarzı hack & slash oyunlara) tarayıcıda saygı duruşu olarak tasarlandı. Oyuncu, Kül Ovaları'nda gölge yaratıklarına karşı savaşır, Karanlık Zindan'da bekleyen Kara Muhafız'a kadar ilerler ve yol boyunca beş nadirlik kademesinde (sıradandan efsaneviye) ganimet toplar.",
      "Sistemin merkezinde derinlik vardır: silah ve zırhlara rastgele ek özellikler (affix) iliştirilir, mücevher soketlenebilir, ekipman yükseltilip büyülenebilir. Karakter seviye atlandıkça hem istatistik hem yetenek puanı kazanır ve dört farklı yetenek açılır. Kalıcılık için görev zincirleri, günlük avlar ve periyodik 'Gölge İstilası' dünya olayları eklendi — böylece oyun tek seferlik değil, geri dönülen bir deneyim hâline geldi. Klavye-fare, gamepad ve mobil dokunmatik kontrollerin hepsi aynı anda desteklenir; ilerleme otomatik kaydedilir.",
      "## BlokKraft: kendi dünyanı inşa et",
      "[BlokKraft](/oyun/ov-blokkraft/blokkraft), Minecraft'ın sevilen sandbox formülünü tarayıcıya taşıyan bir inşa ve keşif oyunudur. Prosedürel olarak üretilen bir dünyada tepeler, göller, plajlar ve ormanlar arasında dolaşırsın; her oturuş farklı bir haritayla başlar.",
      "Oyun iki farklı oynanış tarzı sunar: Toplayıcı modunda blok kırıp envanterine kaynak biriktirir, tahta, cam ve tuğla gibi yeni malzemeler craft edersin; Yaratıcı modunda ise tüm bloklar sınırsızdır ve tek amacın özgürce inşa etmektir. Tam gün-gece döngüsü ve yıldızlı gece gökyüzü, dünyaya yaşayan bir his katar. Dünyan otomatik kaydedilir, böylece kaldığın yerden devam edebilirsin — masaüstünde ve mobilde dokunmatik kontrollerle aynı akıcılıkla çalışır.",
      "## Neden kendi oyunlarımızı yapıyoruz?",
      "Dışarıdan oyun derlemek bir portalın temel işlevidir, ama bizim için yeterli değildi. Oynava Originals, sitenin sadece bir vitrin değil, aynı zamanda bir yapımcı olduğunu göstermek için var. Bu oyunlar başka hiçbir sitede bulunmaz; reklam kuşatması olmadan, gerçekten keyifli bir deneyim sunmayı hedefler.",
      "## Sırada ne var?",
      "Oynava Originals koleksiyonu büyümeye devam edecek. Her yeni yapım, aynı prensiple ilerliyor: özgün bir fikir, özenli bir geliştirme süreci ve tarayıcıda indirmeden oynanan, gerçekten tamamlanmış bir oyun deneyimi. Koleksiyonun tamamını [Oynava Originals kategorisinde](/kategori/originals) bulabilirsin.",
    ],
  },
  {
    slug: "satranc-rehberi-acilis-strateji",
    title: "Satranç Oyunları Rehberi: Temel Açılışlar ve Strateji İpuçları",
    date: "2026-07-09",
    excerpt:
      "Satranca yeni başlayanlar için merkez kontrolü, taş gelişimi ve temel açılış prensipleri — tarayıcıda ücretsiz pratik yapmak için pratik bir rehber.",
    body: [
      "Satranç, binlerce yıldır oynanan ama hiç eskimeyen bir strateji oyunu. Kuralları birkaç dakikada öğrenilir, ama gerçek derinliği anlamak yıllar alabilir. Bu rehber, yeni başlayanların en sık yaptığı hataları önlemesine ve ilk oyunlarında daha bilinçli hamleler yapmasına yardımcı olacak temel prensipleri anlatıyor.",
      "## Açılışta üç temel prensip",
      "Satranç öğreticilerinin neredeyse hepsi aynı üç prensipte birleşir; bunları ezberlemek, açılış teorisini tek tek öğrenmekten çok daha faydalıdır:",
      "- **Merkezi kontrol et:** Tahtanın ortasındaki dört kare (e4, e5, d4, d5), taşlarının en fazla hareket alanına sahip olduğu bölgedir. Piyonlarını erken merkeze doğru ilerletmek, sonraki taşların gelişimini kolaylaştırır.",
      "- **Taşlarını geliştir, aynı taşı tekrar oynatma:** Her hamlede farklı bir taşı oyuna sokmak (at, fil, sonra kale ve vezir) hızlı gelişim sağlar. Açılışta aynı taşı iki-üç kez oynatmak zaman kaybettirir.",
      "- **Şahını erken rok yaptır (castle):** Kralın tahtanın ortasında açıkta kalması tehlikelidir. Genellikle 5-7. hamle civarında rok yaparak hem şahını güvene al hem de kalenizi oyuna sok.",
      "## Sık yapılan başlangıç hataları",
      "Yeni oyuncuların en sık düştüğü tuzak, erken vezir hamleleridir; vezir açılışta öne çıkarılırsa rakip tarafından tempo kazandıracak şekilde kovalanabilir. Bir diğer yaygın hata, kenar piyonlarını (a ve h sütunu) gereksiz yere oynatmaktır — bu hamleler merkezi güçlendirmez ve zaman kaybettirir.",
      "## Taş değişimlerinde basit değer mantığı",
      "Hangi değişimin kârlı olduğunu hızlıca değerlendirmek için piyon=1, at/fil=3, kale=5, vezir=9 gibi kabaca kabul edilen değerleri akılda tutmak yardımcı olur. Eşit veya kârlı bir değişim genellikle güvenlidir; ama pozisyonel faktörler (kralın güvenliği, taş aktivitesi) bazen ham sayısal değerden daha önemli olabilir.",
      "## Oyun ortası ve sonuna doğru",
      "Açılış bittiğinde asıl mücadele başlar. Taşlarını pasif tutmak yerine aktif karelere yönlendirmek, rakibinin zayıf noktalarını (savunmasız piyonlar, açık sütunlar) aramak oyun ortasının temelidir. Oyun sonuna yaklaşırken kralını da aktif bir taş gibi kullanmaya başlamak — artık tehlike azaldığı için — deneyimli oyuncuları yeni başlayanlardan ayıran önemli bir farktır.",
      "## Pratik yapmanın en iyi yolu",
      "Teoriyi okumak faydalıdır ama satranç gerçek oyunla öğrenilir. [Satranç oyunları koleksiyonunda](/satranc-oyunlari) bilgisayara karşı farklı zorluk seviyelerinde ücretsiz pratik yapabilir, öğrendiğin prensipleri gerçek partilerde deneyebilirsin. Her kaybedilen oyun bile bir öğrenme fırsatıdır — hangi hamlenin seni zor duruma soktuğunu geri dönüp incelemek gelişimin en hızlı yoludur.",
    ],
  },
  {
    slug: "sudoku-nasil-cozulur-teknikler",
    title: "Sudoku Nasıl Çözülür? Başlangıçtan İleri Seviyeye Teknikler",
    date: "2026-07-09",
    excerpt:
      "Sudoku bulmacalarını daha hızlı ve tahminsiz çözmek için temel taramadan aday-rakam not almaya kadar pratik teknikler.",
    body: [
      "Sudoku, basit bir kuralla çalışır: 9x9'luk ızgarayı, her satırda, her sütunda ve her 3x3'lük kutuda 1'den 9'a kadar rakamların yalnızca bir kez geçeceği şekilde doldurmak. Kural basit olsa da doğru teknik olmadan bulmaca hızla karmaşıklaşabilir. Bu rehber, tahmine değil mantığa dayanan çözüm tekniklerini anlatıyor.",
      "## Temel teknik: satır-sütun-kutu taraması",
      "En temel yöntem, bir rakamı (örneğin 5'i) sırayla her 3x3 kutuda aramaktır. Bir kutuda 5 rakamının gidebileceği yalnızca tek bir boş hücre kaldıysa (diğerleri aynı satır, sütun veya kutuda zaten dolu ya da engelliyse), o hücreye güvenle 5 yazılabilir. Bu taramayı 1'den 9'a kadar her rakam için tekrarlamak, bulmacanın büyük kısmını tahmin gerektirmeden çözer.",
      "## Aday rakamları not almak",
      "Bulmaca zorlaştıkça tek bakışta çözüm bulmak zorlaşır. Bu noktada her boş hücreye küçük rakamlarla 'aday' olabilecek sayıları not almak (örneğin bir hücreye 2, 4, 7 gibi olası üç rakamı yazmak) büyük kolaylık sağlar. Bir hücrede yalnızca tek bir aday kaldığında, o hücrenin cevabı kesinleşmiş demektir.",
      "## Çift ve üçlü teknikleri",
      "İleri seviye bir teknik olan 'çıplak çift' (naked pair), aynı satır, sütun veya kutuda iki hücrenin yalnızca aynı iki aday rakama sahip olduğu durumları arar. Bu iki rakam kesin olarak bu iki hücreden birine ait olacağı için, aynı bölgedeki diğer hücrelerden bu iki rakam güvenle silinebilir. Aynı mantık üç hücre ve üç rakam için 'çıplak üçlü' olarak da uygulanabilir; bu teknikler, tıkanan bulmacaları genellikle yeniden ilerletir.",
      "## Sık yapılan hatalar",
      "En yaygın hata, henüz kesinleşmemiş bir rakamı 'muhtemelen doğrudur' diyerek erken yazmaktır; bu tek hata, bulmacanın geri kalanını tamamen bozabilir ve nereden yanlış gittiğini bulmak zaman alır. Bir diğer hata, yalnızca satırlara odaklanıp 3x3 kutuları ihmal etmektir — üç kısıtı (satır, sütun, kutu) birlikte düşünmek çözümü hızlandırır.",
      "## Pratik yapmaya nereden başlamalı",
      "Kolay seviyeden başlayıp temel taramayı otomatik hâle getirdikten sonra orta ve zor seviyelere geçmek en sağlıklı öğrenme yoludur. [Sudoku oyunları koleksiyonunda](/sudoku-oyunlari) farklı zorlukta bulmacaları ücretsiz deneyebilir, zamanla tahmin etmeden, tamamen mantıkla çözen bir oyuncu hâline gelebilirsin.",
    ],
  },
];
